---
title: "fractures"
author: "George"
date: "2023-03-17"
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
    theme: spacelab
    highlight: textmate
    df_print: paged
    code_folding: hide
    self_contained: false
    keep_md: false
    encoding: "UTF-8"
---

```{r set-up}
library(tidyverse)
source("../../Protocols/theme.R")

cols.phylum <- c( # Sorted on abundance
  "Proteobacteria" = "#C7B19C",
  "Actinobacteriota" = "#A2A475",
  "Bacteroidota" = "#972D15",
  "Cyanobacteria" = "#D69C4E",
  "Firmicutes" = "#1B5331",
  "Myxococcota" = "#00A08A",
  "Patescibacteria" = "#D8B70A",
  "Other" = "#899DA4"
)

cols.order <- c( # Sorted on abundance (descending)
  "Burkholderiales" = "#C7B19C",
  "Sphingomonadales" = "#A2A475",
  "Mycobacteriales" = "#972D15",
  "Rhizobiales" = "#D69C4E",
  "Bacillales" = "#1B5331",
  "Cyanobacteriales" = "#00A08A",
  "Actinomycetales" = "#D8B70A",
  "Flavobacteriales" = "#FAEFD1",
  "Pseudomonadales" = "#046C9A",
  "Other" = "#899DA4"  
) %>% rev()

cols.rock <- c(
  "Turbiditic greywackes" = "#046C9A", 
  "Alum shale" = "#1B5331", 
  "Imbricates: sandstone + conglomerate" = "#D69C4E", 
  "Ignimbrite + porphyry" = "#972D15", 
  "Dolerite" = "#A2A475",
  "Ignimbrites + volcanic porphyries" = "#972D15"
)
```


```{r read input files}
# GTDB release 207 was used as reference database

# ASV table
seqtab <- read_tsv("data/ASV_table.tsv", col_types = cols(.default = col_character(), count = col_integer()))
# Taxonomy
gtdb <- read_tsv("data/ASV_tax.tsv", col_types = cols(.default = col_character()))
# Metadata for plotting
meta <- read_tsv("data/metadata.tsv", col_types = cols(.default = col_character())) %>%
  filter(sample != "P28309_1045")

# Negative extraction control
ncontrol <- seqtab %>% 
  filter(sample == "P28309_1057_S57" | sample == "P28309_1049_S49") %>%
  mutate(sample = gsub("_S[0-9].", "", sample))

meta <- meta %>%
  mutate(type = factor(type, levels = c("fracture", "fluid", "control"))) %>%
  arrange(type)

# Tidy ASV table
seqtab <- seqtab %>%
  mutate(sample = gsub("_S[0-9].", "", sample)) %>%
  filter(sample %in% meta$sample) 
```


```{r fractures cosc}
# Biofilms (n = 7) included are 3, 4, 5, 8, 12, 13, and 17
# Biofilm 3 and 4 share the mud pit sample
fractures <- seqtab %>%
  # Start with removing the ASVs in the negative extraction controls
  # Removal of ASVs from drilling fluid (pairwise)
  filter(
    sample %in% c("P28309_1050","P28309_1051") & !seqid %in% seqtab[seqtab$sample == "P28309_1042",]$seqid |
      sample == "P28309_1052" & !seqid %in% seqtab[seqtab$sample == "P28309_1043",]$seqid |
      sample == "P28309_1053" & !seqid %in% seqtab[seqtab$sample == "P28309_1044",]$seqid |
      sample == "P28309_1054" & !seqid %in% seqtab[seqtab$sample == "P28309_1046",]$seqid |
      sample == "P28309_1055" & !seqid %in% seqtab[seqtab$sample == "P28309_1047",]$seqid |
      sample == "P28309_1056" & !seqid %in% seqtab[seqtab$sample == "P28309_1048",]$seqid
      ) 

# Drilling fluid microscopy counts
# 940 µl drilling fluid fixed with 60 µl 37% formaldehyde
# Conversion factor microscopy for 5 x 5 raster: 36019.34
# So one cell counted in the raster corresponds with: (cells per ml) (1 x 36019.34) / 0.94
dfluid <- read_tsv("data/contamination.tsv", col_types = cols(.default = col_double(), coreid = col_character())
                   )

# Fluorescent microsphere counts
# Core 1-16 with counts from the drilling fluid combined with the core sample
# Core 17-50 with counts from the microsphere bag (before / after)
# Cores 12-16 plus 32 with no bead count (in total n = 44)


# Add drilling fluid samples
fractures <- seqtab %>%
  filter(!seqid %in% ncontrol) %>% # Remove ASVs from the negative extraction control
  inner_join(meta, by = "sample") %>%
  filter(type == "fluid") %>% select(seqid, sample, count) %>%
  rbind(fractures) %>%
  rbind(ncontrol)

# Add relative abundance
fractures <- fractures %>%
  group_by(sample) %>% 
  mutate(relab = count / sum(count)) %>%
  ungroup()
```


```{r logging}
# Read raw data from ICDP
# https://www.icdp-online.org/projects/by-continent/europe/cosc-sweden
# Cite the operational data sets

logging <- read_tsv("data/5054_2_A-Composite Log.asc", show_col_types = F) %>% 
  select(depth = Depth, temp = Temp.MS) %>%
  filter(depth != "m") %>%
  mutate(temp = as.double(temp)) %>% filter(temp != -999.25) %>%
  mutate(depth = as.double(depth))

# Add lithology
logging <- logging %>%
  mutate(rock = case_when(
    depth <= 780 ~ "Turbiditic greywackes",
    depth > 780 & depth <= 825 ~ "Alum shale",
    depth > 825 & depth <= 1250 ~ "Imbricates: sandstone + conglomerate",
    depth > 1250 & depth <= 1600 ~ "Ignimbrite + porphyry",
    depth > 1600 & depth <= 1930 ~ "Dolerite",
    .default = "Ignimbrites + volcanic porphyries"
  ))

lithology <- list(depth = c(780, 45, 425, 350, 330, 346),
                  rock = c("Turbiditic greywackes", "Alum shale",
                  "Imbricates: sandstone + conglomerate", "Ignimbrite + porphyry",
                  "Dolerite", "Ignimbrites + volcanic porphyries"))
```

### Fig. 3 ###


```{r nmds fractures unfiltered}
set.seed(999)
nmds <- seqtab %>% # Full size fraction
  select(seqid, sample, count) %>% spread(seqid, count, fill = 0) %>%
  column_to_rownames("sample") %>% vegan::metaMDS()

vegan::scores(nmds)$sites %>%
  as.data.frame() %>%
  rownames_to_column("sample") %>%
  inner_join(meta, by = "sample") -> nmds.scores
```

Plot the ordination

```{r plot nmds unfiltered, include = T}
p1 <- nmds.scores %>%
  ggplot(aes(NMDS1, NMDS2, shape = type)) +
  geom_vline(xintercept = 0, linetype = 'dotted') +
  geom_hline(yintercept = 0, linetype = 'dotted') +
  # Points for samples, coloured by nature
  geom_point(size = 3) +
  theme_tidy() +
  ggrepel::geom_label_repel(aes(label = depth), color = "black",
                  box.padding = 0.4, label.padding = 0.1, 
                  max.overlaps = 10,
                  min.segment.length = 0.3,
                  size = 7/.pt) +
 scale_shape_manual(values = c("fracture" = 17, "fluid" = 19, "control" = 4), 
                     name = "", guide = "none",
                     labels = c("Fracture", "Drilling fluid", "Neg. control")) +
  annotate('text', x = -Inf, y = -Inf, size = 7/.pt, 
           label = paste('Stress = ', round(nmds$stress, digits = 2)),
           hjust = -0.1, vjust = -1,
           )
```


```{r nmds fractures filtered}
set.seed(999)
nmds <- fractures %>% select(-relab) %>%
  spread(seqid, count, fill = 0) %>%
  column_to_rownames("sample") %>% vegan::metaMDS()

nmds.scores <- vegan::scores(nmds)$sites %>%
  as.data.frame() %>%
  rownames_to_column("sample") %>%
  inner_join(meta, by = "sample")
```


```{r plot nmds filtered, include = T}
p2 <- nmds.scores %>%
  ggplot(aes(NMDS1, NMDS2, shape = type)) +
  geom_vline(xintercept = 0, linetype = 'dotted') +
  geom_hline(yintercept = 0, linetype = 'dotted') +
  stat_ellipse(aes(x = NMDS1, y = NMDS2, colour = type), 
               geom = "polygon", show.legend = F, level = 0.85,
               fill = NA, linetype = "dashed") +  
  # Points for samples, coloured by nature
  geom_point(size = 3) +
  theme_tidy() +
  ggrepel::geom_label_repel(aes(label = depth), color = "black",
                  box.padding = 0.4, label.padding = 0.1, 
                  max.overlaps = 10,
                  min.segment.length = 0.3,
                  size = 7/.pt) +
  scale_shape_manual(values = c("fracture" = 17, "fluid" = 19, "control" = 4), 
                     name = "",
                     labels = c("Fracture", "Drilling fluid", "Neg. control")) +
  scale_color_manual(values = c(fracture = "#D69C4E", fluid = "#A2A475"), guide = "none") +
  annotate('text', x = -Inf, y = -Inf, size = 7/.pt, 
           label = paste('Stress = ', round(nmds$stress, digits = 2)),
           hjust = -0.1, vjust = -1,
           ) +
  theme(axis.title.y = element_blank())
```


```{r merge ordination plots, fig.width=18/2.53}
library(patchwork)
p1 + p2 + plot_layout(guides = "collect") & 
  theme(legend.position = "bottom")
```


```{r export ordination}
ggsave("figures/nmds_fractures.pdf", width = 17, height = 10, units = "cm")
```


```{r communities order}
i <- meta %>% pull(sample)

fractures %>%
  inner_join(gtdb, by = "seqid") %>%
  group_by(order, sample) %>%
  # Sum the abundance of each phylum within a sample
  summarise(relab = sum(relab), .groups = 'drop_last') %>%
  # Calculate the mean abundance of each phylum over the categories
  summarise(mean_relab = sum(relab), .groups = 'drop') %>%
  filter(!is.na(order)) %>%
  top_n(9, mean_relab) -> t

gtdb %>%
  left_join(t %>% transmute(order, topphylum = order), by = "order") %>%
  replace_na(list("topphylum" = "Other")) -> taxref
```


```{r plot communities order}
fractures %>%
  inner_join(taxref, by = "seqid") %>%
  # Summarize in order to have the sum for each category and topphylum
  group_by(sample, topphylum) %>% 
  summarise(relab = sum(relab), .groups = 'drop_last') %>%
  inner_join(meta, by = "sample") %>%
  # Call the plot
  ggplot(aes(x = fct_relevel(sample, i),
             y = relab * 100, 
             fill = fct_relevel(topphylum, names(cols.order)),
             label = substr(name, 3, nchar(name))
             )
         ) +
  labs(x = '', y = 'Relative abundance (%)', fill = "Order") +
  geom_col() +
  geom_text(data = meta, 
            aes(x = sample, y = -3, label = depth), 
            size = 7/.pt, inherit.aes = F) +
  scale_fill_manual(values = cols.order) +
  annotate("segment", x =  0.55, xend =   7.45, y = 101, yend = 101) +
  annotate("segment", x =  7.55, xend =  13.45, y = 101, yend = 101) +
  annotate("segment", x = 13.55, xend =  15.45, y = 101, yend = 101) +
  annotate('text', x =  3.95, y = 104, size = 7 / .pt, label = "Fractures") +
  annotate('text', x = 10.45, y = 104, size = 7 / .pt, label = "Drilling fluid") +
  annotate('text', x = 14.45, y = 104, size = 7 / .pt, label = "Neg. controls") +
  theme_tidy(ratio = 0.8, legend = "bottom") + guides(fill = guide_legend(ncol = 3)) +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    legend.key.height = unit(4, "mm"),
    legend.margin = margin(0,0,0,-4)
    )
```


```{r export bar plot}
ggsave("figures/cosc_fractures.pdf", width = 12, height = 12, units = "cm")
```


```{r stat beta diversity}
seqtab %>%
  inner_join(meta[,c("sample","type")], by = "sample") %>% 
  spread(seqid, count, fill = 0) %>%
  column_to_rownames("sample") -> t

set.seed(999)
vegan::adonis2(t[,c(-1)] ~ type, data = t)

fractures %>%
  select(-relab) %>%
  inner_join(meta[,c("sample","type")], by = "sample") %>% 
  spread(seqid, count, fill = 0) %>%
  column_to_rownames("sample") -> t

set.seed(111)
vegan::adonis2(t[,c(-1)] ~ type, data = t)

```


### Fig. 1 ###


```{r plot depth profile}
p1 <- logging %>%
  mutate(depth = depth / 1000) %>% # Depth in km
  ggplot(aes(temp, depth)) +
  geom_line() + scale_y_reverse() + scale_x_continuous(position = "top") +
  labs(x = "Temperature (°C)", y = "Depth (km)") +
  theme_tidy(ratio = 2) +
  theme(
    panel.border = element_blank(),
    axis.line = element_line(),
    panel.grid.major.y = element_line(colour = "grey", linetype = "dotted", linewidth = 0.4)
  )
```


```{r plot lithology}
p2 <- lithology %>%
  data.frame() %>%
  mutate(sample = "hi") %>%
  mutate(depth = depth / 1000) %>% # Depth in km
  mutate(rock = factor(rock, rev(names(cols.rock)))) %>%
  ggplot(aes(sample, depth, fill = rock)) +
  geom_col() + scale_y_reverse() + scale_x_discrete(position = "top") +
  labs(x = "Lithology", y = "", fill = "") +
  theme_tidy(ratio = 6) + 
  guides(fill = guide_legend(reverse = T)) +
  scale_fill_manual(values = cols.rock) + 
  annotate("text", x = 1.5, y = 1.268, label = "-") +
  annotate("text", x = 1.5, y = 1.270, label = "-") +
  annotate("text", x = 1.5, y = 1.311, label = "-") +
  annotate("text", x = 1.5, y = 1.537, label = "-") +
  annotate("text", x = 1.5, y = 1.605, label = "-") +
  annotate("text", x = 1.5, y = 1.608, label = "-") +
  annotate("text", x = 1.5, y = 1.669, label = "-") +
  theme(
    panel.border = element_blank(),
    axis.line.x = element_line(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
    )
```


```{r plot scandinavia}
# Äspö Lat N 57.4334, Lon E 16.6603) 
baltic <- list.files("../../Cultures/didactic-spork/data/shapefiles/", pattern = ".shp", full.names = TRUE) %>% lapply(sf::st_read)
# Use EPSG 3152, unit (m)
baltic[[3]] <- baltic[[3]] %>% sf::st_transform(3152)
baltic[[6]] <- baltic[[6]] %>% sf::st_transform(3152)
baltic[[7]] <- baltic[[7]] %>% sf::st_transform(3152)

ggplot() + # x (longitude), y (latitude)
  geom_sf(data = baltic[[3]], colour = "black", fill = "white", lwd = 0.08) + # Finland
  geom_sf(data = baltic[[6]], colour = "black", fill = "white", lwd = 0.08) + # Norway
  geom_sf(data = baltic[[7]], colour = "black", fill = "white", lwd = 0.08) + # Sweden
  ggspatial::annotation_scale(location = "br") +
  annotate("rect", xmin = -126780 - 20000, xmax = -126780 + 20000, ymin = 530561 - 20000, ymax = 530561 + 20000, fill = "black" 
           ) +
  annotate("text", x = -126780 + 110000, y = 530561, label = "COSC-2", colour = "black", size = 7/.pt) +
  lims(x = c(-605927, 377430), y = c(-300000, 1172471)) +
  labs(x = "", y = "") + 
  theme(
    panel.grid = element_line(colour = "#D9D9D9", linewidth = 0.4),
    panel.background = element_blank(),
    axis.text = element_text(size = 7, color = "black"),
    axis.ticks = element_blank()
    )
```

```{r export map}
ggsave("coscmap.png", width = 8, height = 8, units = "cm")
```



```{r plot fig. 1b}
library(patchwork)
p1 + p2 & theme(legend.position = "none")
```
```{r export fig. 1b}
ggsave("fig1b.pdf", width = 8, height = 10, units = "cm")
```


### Fig. 2 ###

```{r, fig.height=8/2.54, fig.width=8/2.54}
p1 <- dfluid %>%
  ggplot(aes(depth, cells)) +
  geom_point() + scale_y_log10() +
  labs(x = "Core depth (m)", y = expression("Cells in drilling fluid (ml"^"-1"*")")) +
  theme_tidy()

p2 <- dfluid %>%
  ggplot(aes(depth, quenched)) +
  geom_point() +
  geom_vline(xintercept = 750, linetype = "dotted") +
  labs(x = "Core depth (m)", y = "Fraction of beads quenced") +
  annotate("text", x = 350, y = 0.925, 
           label = "Beads added\nto drilling fluid", 
           size = 7/.pt) +
  annotate("text", x = 1200, y = 0.925, 
           label = "Core immersed\nin bead bath", 
           size = 7/.pt) +
  theme_tidy()

p3 <- dfluid %>%
  mutate(left = (1-quenched) * cells) %>%
  ggplot(aes(depth, left)) +
  geom_point() +
  geom_vline(xintercept = 750, linetype = "dotted") +
  labs(x = "Core depth (m)", y = expression("Cells left from drilling fluid (ml"^"-1"*")")) +
  theme_tidy()
```


```{r, fig.width=18/2.53}
library(patchwork)
p1 + p2 + p3 + plot_annotation(tag_levels = c("a","b","c")) & 
  theme(plot.tag.position = "top")
```
```{r export fig. 2}
ggsave("figures/mudpit.pdf", height = 14, width = 14, units = "cm")
```

